### ISSUE TITLE
exception on using statement

### ISSUE THREAD

**Issue by RHill051** [gsuitedevs/dotnet-samples#2]
Hey guys, I followed the steps to execute the sample code and I'm getting an error surrounding the "client_secret.json" 
"Could not find file 'C:\\Googel Calendar App\\Google Calendar\\Google Calendar\\bin\\Debug\\client_secret.json'.":"C:\\Googel Calendar App\\Google Calendar\\Google Calendar\\bin\\Debug\\client_secret.json"
Any advice on this would be greatly appreciated.

**Comment by grant** [comment]
Which sample? I think the downloaded file should be renamed `client_secret.json`.

We may change the code to work with this name.

**Comment by RHill051** [comment]
sorry, I was referring to the sample found here. https://developers.google.com/calendar/quickstart/dotnet. I'll try renaming the credentials.json

**Comment by RHill051** [comment]
renaming the credentials.json file fixed that issue but now I'm getting an exception when executing request.Executre(); on line 59 of the sample code. not sure what is missing from the tutorial. Any ideas?

**Comment by joshuanoelsantos** [comment]
Hi RHill051, I have same experience with you. I got the first error you described which was solved by renaming the downloaded file and got the next error you mentioned.

This error is caused by the Gmail API not Enabled yet. You could google how to enable it or try this url https://console.developers.google.com/apis/library/gmail.googleapis.com.

If you have solved your last error then that is awesome. I just need to make this comment for anyone who receives this kind of errors. Hopefully Google guys will  update their documentation by changing the name of the downloaded file and making sure that the Enable API button in the quickstart page really does enable the the Gmail API.

**Comment by erickoledadevrel** [comment]
Sorry for the problems you encountered. We fixed the button to correctly enable the API, and the code now looks for a file called `credentials.json`. Let me know if you still have problems.
